version: 1
applications:
  - appRoot: apps/rent-app
    frontend:
      phases:
        preBuild:
          commands:
            # Install pnpm
            - npm install -g pnpm@9.15.0
            # Install dependencies
            - pnpm install --frozen-lockfile
        build:
          commands:
            # Generate Prisma client
            - cd apps/rent-app && pnpm db:generate
            # Build the application
            - cd ../.. && pnpm build:rent
      artifacts:
        baseDirectory: apps/rent-app/.next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - apps/rent-app/node_modules/**/*
          - packages/*/node_modules/**/*
          - .pnpm-store/**/*
    customHeaders:
      - pattern: '**/*'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
          - key: 'X-Frame-Options'
            value: 'DENY'
          - key: 'X-Content-Type-Options'
            value: 'nosniff'
          - key: 'Referrer-Policy'
            value: 'strict-origin-when-cross-origin'
          - key: 'Permissions-Policy'
            value: 'camera=(), microphone=(), geolocation=()'
    environmentVariables:
      # Build-time variables
      - name: NODE_ENV
        value: production
      - name: NEXT_TELEMETRY_DISABLED
        value: '1'
      # Database
      - name: DATABASE_URL
        value: '${DATABASE_URL}'
      # NextAuth
      - name: AUTH_SECRET
        value: '${AUTH_SECRET}'
      - name: NEXTAUTH_URL
        value: '${NEXTAUTH_URL}'
      # OAuth
      - name: GOOGLE_CLIENT_ID
        value: '${GOOGLE_CLIENT_ID}'
      - name: GOOGLE_CLIENT_SECRET
        value: '${GOOGLE_CLIENT_SECRET}'
      - name: GITHUB_ID
        value: '${GITHUB_ID}'
      - name: GITHUB_SECRET
        value: '${GITHUB_SECRET}'
      # Stripe
      - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        value: '${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
      - name: STRIPE_SECRET_KEY
        value: '${STRIPE_SECRET_KEY}'
      - name: STRIPE_WEBHOOK_SECRET
        value: '${STRIPE_WEBHOOK_SECRET}'
      # Firebase
      - name: NEXT_PUBLIC_FIREBASE_API_KEY
        value: '${NEXT_PUBLIC_FIREBASE_API_KEY}'
      - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: '${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: '${NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: '${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: '${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - name: NEXT_PUBLIC_FIREBASE_APP_ID
        value: '${NEXT_PUBLIC_FIREBASE_APP_ID}'
      - name: FIREBASE_ADMIN_PRIVATE_KEY
        value: '${FIREBASE_ADMIN_PRIVATE_KEY}'
      - name: FIREBASE_ADMIN_CLIENT_EMAIL
        value: '${FIREBASE_ADMIN_CLIENT_EMAIL}'
      # AWS Services
      - name: AWS_REGION
        value: '${AWS_REGION}'
      - name: AWS_S3_BUCKET
        value: '${AWS_S3_BUCKET}'
      - name: AWS_SES_REGION
        value: '${AWS_SES_REGION}'
      - name: AWS_SES_FROM_EMAIL
        value: '${AWS_SES_FROM_EMAIL}'
      # Application
      - name: LAUNCHED
        value: '${LAUNCHED}'
